pub mod add_binary;
pub mod compare_keystrokes;
pub mod correct_capitalization;
pub mod first_unique_char;
pub mod intersection;
pub mod jewels_and_stones;
#[cfg(feature = "nightly")]
pub mod merge_linked_lists;
pub mod prefix;
pub mod removal_palindrome;
#[cfg(feature = "nightly")]
pub mod remove_rev;
#[cfg(feature = "nightly")]
pub mod remove_val;
pub mod reverse_string;
pub mod spot_diff;
pub mod two_sum;
pub mod uncommon_words;
pub mod vacuum_route;
pub mod valid_anagram;
pub mod valid_palindrome;
pub mod validate_chars;
